[package]
name = "terminal-app"
version = "0.1.0"
edition = "2021"
authors = ["Jacek Kurlit"]
description = "Terminal application that give access to sms api"

[dependencies]
clap = { version = "4.1.13", features = ["derive"] }
anyhow = "1.0.70"
sms-api = { path = "../sms-api" }
